language: python
python:
  - '2.7'
  - '3.5'

before_install:
  - sudo apt-get install -qq libblas3gf
  - pip install coveralls

install: pip install -r requirements.txt

script: make test

after_success: coveralls

notifications:
  email:
    recipients:
      - bbengfort@districtdatalabs.com
      - tojeda@districtdatalabs.com
      - rbilbro@districtdatalabs.com
    on_success: change
    on_failure: always
